apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-study-app
  namespace: production
spec:
  selector:
    matchLabels:
      app: k8s-study
  template:
    metadata:
      name: k8s-study-app-pod
      labels:
        app: k8s-study
    spec:
      containers:
        - name: k8s-study-app-container
          image: 2hongjae/k8s-study:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080 # does not affect actual port
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-study-svc-nodeport
  namespace: production
spec:
  selector:
    app: k8s-study
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
